name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Fetch Tags
      run: git -c protocol.version=2 fetch --tags --progress --no-recurse-submodules origin
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Release Version
      id: get_version
      run: VERSION=$(./gradlew currentVersion | grep 'version:' | cut -d ' ' -f 3) && echo ::set-output name=VERSION::$VERSION
    - name: Upload zip
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: rd-${{ steps.get_version.outputs.VERSION }}.zip
        # Directory containing files to upload
        path: rd-cli-tool/build/distributions/rd-${{ steps.get_version.outputs.VERSION }}.zip
    - name: Upload jar
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: rundeck-cli-${{ steps.get_version.outputs.VERSION }}.jar
        # Directory containing files to upload
        path: rd-cli-tool/build/libs/rundeck-cli-${{ steps.get_version.outputs.VERSION }}.jar
    - name: Upload api-lib
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: rd-api-client-${{ steps.get_version.outputs.VERSION }}.jar
        # Directory containing files to upload
        path: rd-api-client/build/libs/rd-api-client-${{ steps.get_version.outputs.VERSION }}.jar
